apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::361769590037:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-pDOFAKyMDrfP
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::361769590037:user/Ravindra
      username: Ravindra  
kind: ConfigMap
metadata:
  creationTimestamp: "2025-04-01T03:36:24Z"
  name: aws-auth
  namespace: kube-system
  uid: 0edfcb68-e9ee-49f7-a0b3-cf6858167aff